---
- name: Convert CentOS 7 to RHEL 7 using the convert2rhel
  hosts: all
  become: yes
  roles:
    - role: convert2rhel
      vars:
        rhel_org: MY_ORG
        rhel_activation_key: MY_ACTIVATION_KEY
        rhel_username: MY_USERNAME
        rhel_password: MY_PASSWORD
