---
- name: Download Convert2RHEL repository definition
  hosts: all
  become: yes
  vars:
    rhel_org: MY_ORG
    rhel_activation_key: MY_ACTIVATION_KEY
    rhel_username: MY_USERNAME
    rhel_password: MY_PASSWORD
    gpg_key_url: "https://www.redhat.com/security/data/fd431d51.txt"
    uep_cert_url: "https://ftp.redhat.com/redhat/convert2rhel/redhat-uep.pem"
    convert2rhel_repo_url: "https://ftp.redhat.com/redhat/convert2rhel/7/convert2rhel.repo"

  tasks:
    - name: Verify CentOS version
      command: cat /etc/centos-release
      register: centos_version
      failed_when: "'CentOS' not in centos_version.stdout"
      tags: precheck

    - name: Display CentOS version
      debug:
        msg: "CentOS version is: {{ centos_version.stdout }}"
      tags: precheck

    - name: Update system packages
      yum:
        name: "*"
        state: latest
      tags: update

    - name: Download Red Hat GPG key
      get_url:
        url: "{{ gpg_key_url }}"
        dest: "/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release"
      tags: setup

    - name: Ensure /etc/rhsm/ca directory exists
      file:
        path: /etc/rhsm/ca
        state: directory
        mode: "0755"
      tags: setup

    - name: Download Red Hat UEP certificate
      get_url:
        url: "{{ uep_cert_url }}"
        dest: "/etc/rhsm/ca/redhat-uep.pem"
      tags: setup

    - name: Download Convert2RHEL repository definition
      get_url:
        url: "{{ convert2rhel_repo_url }}"
        dest: "/etc/yum.repos.d/convert2rhel.repo"
      tags: setup

    - name: Verify Convert2RHEL repository configuration
      command: yum repoinfo convert2rhel-for-rhel-7-rpms
      register: repo_info
      changed_when: false
      tags: setup

    - name: Display repository info
      debug:
        msg: "Repository info: {{ repo_info.stdout }}"
      tags: setup

    - name: Install Convert2RHEL
      yum:
        name: convert2rhel
        state: present
      tags: install

    - name: Create Convert2RHEL configuration file
      copy:
        dest: /etc/convert2rhel.ini
        content: |
          [subscription_manager]
          username = {{ rhel_username }}
          password = {{ rhel_password }}
        mode: "0600"
      tags: config

    - name: Run Convert2RHEL
      shell: >
        convert2rhel --auto-attach --username={{ rhel_username }} --config-file /etc/convert2rhel.ini -y
      ignore_errors: yes

    - name: Reboot the system
      reboot:
        msg: "Rebooting to complete the conversion to RHEL 7."
        reboot_timeout: 300
      notify:
        - Remove GPG key
        - Remove Convert2RHEL repository
        - Remove Convert2RHEL package
      tags: reboot

    - name: Verify the new OS version
      command: cat /etc/*release*
      register: new_os_version
      tags: postcheck

    - name: Display the new OS version
      debug:
        msg: "New OS version: {{ new_os_version.stdout }}"
      tags: postcheck

    - name: Verify Red Hat subscription status
      command: subscription-manager status
      register: subscription_status
      tags: postcheck

    - name: Display subscription status
      debug:
        msg: "Subscription status: {{ subscription_status.stdout }}"
      tags: postcheck

    - name: Verify enabled repositories
      command: yum repolist
      register: repo_list
      tags: postcheck

    - name: Display enabled repositories
      debug:
        msg: "Enabled repositories: {{ repo_list.stdout }}"
      tags: postcheck

  handlers:
    - name: Remove GPG key
      ansible.builtin.file:
        path: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release
        state: absent

    - name: Remove Convert2RHEL repository
      ansible.builtin.file:
        path: /etc/yum.repos.d/convert2rhel.repo
        state: absent

    - name: Remove Convert2RHEL package
      ansible.builtin.package:
        name: convert2rhel
        state: absent
