---
- name: Update CentOS repository files
  hosts: all
  become: yes
  tasks:
    - name: Find repository files on remote host
      ansible.builtin.find:
        paths: /etc/yum.repos.d/
        patterns: '*.repo'
      register: repo_files

    - name: Replace mirror.centos.org with vault.centos.org in repo files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: 'mirror\.centos\.org'
        replace: 'vault.centos.org'
        backup: yes
      loop: "{{ repo_files.files }}"

    - name: Uncomment baseurl lines in repo files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^#(baseurl=http.*)'
        replace: '\1'
        backup: yes
      loop: "{{ repo_files.files }}"

    - name: Comment out mirrorlist lines in repo files
      ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: '^(mirrorlist=http)'
        replace: '#\1'
        backup: yes
      loop: "{{ repo_files.files }}"

    - name: Clean yum cache
      ansible.builtin.command: yum clean all

    - name: Update all packages using yum
      ansible.builtin.yum:
        name: '*'
        state: latest